<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="GOGU" failures="1" tests="3" name="Error Validations Test" time="76.663" errors="0" timestamp="2022-12-15T17:47:07 CST">
  <testcase classname="ecommerce.Tests.ErrorValidationsTest" name="LoginErrorValidation" time="0.918"/>
  <testcase classname="ecommerce.Tests.ErrorValidationsTest" name="ProductErrorValidation" time="14.512">
    <skipped/>
  </testcase> <!-- ProductErrorValidation -->
  <testcase classname="ecommerce.Tests.ErrorValidationsTest" name="ProductErrorValidation" time="10.223">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ecommerce.Tests.ErrorValidationsTest.ProductErrorValidation(ErrorValidationsTest.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ProductErrorValidation -->
</testsuite> <!-- Error Validations Test -->
